### ISSUE TITLE
ModuleNotFoundError: No module named 'browsermobproxy'

### ISSUE THREAD

**Issue by JingqiongWang** [Python3WebSpider/BrowserMobProxyTest#1]
Traceback (most recent call last):
  File "。。。/BrowserMobProxyTest/framework.py", line 69, in <module>
    f = Framework()
  File "。。。/BrowserMobProxyTest/framework.py", line 16, in __init__
    self.server.start()
  File "C:\anaconda3\lib\site-packages\browsermobproxy\server.py", line 122, in start
    raise ProxyServerError(message)
browsermobproxy.exceptions.ProxyServerError: The Browsermob-Proxy server process failed to start. Check <_io.TextIOWrapper name='C:\\Users\\59333\\Desktop\\BrowserMobProxyTest\\server.log' mode='w' encoding='cp936'>for a helpful error message.
Exception ignored in: <bound method BaseFramework.__del__ of <__main__.Framework object at 0x00000120ACFD08D0>>
Traceback (most recent call last):
  File "。。。/BrowserMobProxyTest/framework.py", line 43, in __del__
    self.proxy.close()
AttributeError: 'Framework' object has no attribute 'proxy'

**Comment by rogergong1982** [comment]
去server.log看看说什么
